### ISSUE TITLE
main.js

### ISSUE THREAD

**Issue by Gr-Nobel** [ConnorMeyers/obsidian-chorded-hotkeys#1]
wanted to try this out.
can't find the main.js file

**Comment by Gr-Nobel** [comment]
**Update**
I installed this plugin with [BRAT](https://github.com/TfTHacker/obsidian42-brat)
It's working fine on my Windows Machine.

**Comment by TreyMeyers** [comment]
Yes, you can install this via [BRAT](https://github.com/TfTHacker/obsidian42-brat), or find the necessary files on the [releases](https://github.com/ConnorMeyers/obsidian-chorded-hotkeys/releases) page.
