### ISSUE TITLE
Making it work with international characters

### ISSUE THREAD

**Issue by huyz** [ConnorMeyers/obsidian-chorded-hotkeys#2]
On Mac, I'm trying to use the chord `<M-o>c`, which is basically holding the ⌥ key, pressing o.  In macOS, this creates the accented character `ø`.  But I tried `øc` and that doesn't work.

**Comment by TreyMeyers** [comment]
Special characters should already work as expected. I believe the issue here is that event keys (shift, cmd, ctrl, etc.) are not currently supported. Triggering chords via event keys does not align with the intent of this plugin, as those use cases are already covered by built-in hotkey features.
