### ISSUE TITLE
[FR] make it work in "normal" mode for vim keybindings

### ISSUE THREAD

**Issue by huyz** [ConnorMeyers/obsidian-chorded-hotkeys#3]
I use vim keybindings. The plugin works in "insert mode" but doesn't work in "normal mode".

**Comment by TreyMeyers** [comment]
This plugin was initially planned with just text-expander functionality, at the time it didn't make sense to run chords outside of character input in a markdown editor.

With the introduction of command chords, I see the value in allowing chords outside of a markdown editor. 
I've added "support for using command templates outside of a markdown editor" to the roadmap.

I added "vim support" as its own entry in the roadmap as there are additional issues in preventing vim input when a chord is executed.

**Comment by huyz** [comment]
Actually making it work in vim normal mode is no longer a priority for me as I found that Obsidian Vimrc Support handles that just fine. 

Feel free to close this issue
