### ISSUE TITLE
How does this plugin compare with its counterparts ?

### ISSUE THREAD

**Issue by ngirard** [ConnorMeyers/obsidian-chorded-hotkeys#5]
There are currently 4 plugins that apparently provide the same functionality.
Unfortunately, there is currently no information that would help to make an informed choice among them.
Could you please explain how your plugin differs from its counterparts ?

Here are the information I gathered about the aforementioned plugins, yours included:

**Chorded hotkeys**
DL:: 261
Updated:: 3 months ago
Issues:: 2
Commits:: 9
Version:: 1.0.0
obsidian://show-plugin?id=obsidian-chorded-hotkeys
https://github.com/ConnorMeyers/obsidian-chorded-hotkeys

**Sequence hotkeys**
DL:: 954
Updated:: 3 months ago
Issues:: 9
Commits:: 60
Version:: 0.5.1
obsidian://show-plugin?id=obsidian-sequence-hotkeys
https://github.com/moolmanruan/obsidian-sequence-hotkeys

**Hotkeys chords**
DL:: 446
Updated:: a year ago
Issues:: 2
Commits:: 47
Version:: 0.1.0
obsidian://show-plugin?id=obsidian-hotkeys-chords
https://github.com/trenta3/obsidian-hotkeys-chords

**Key sequence shortcut**
DL:: 840
Updated:: a year ago
Issues:: 6
Commits:: 18
Version:: 2.0.2
obsidian://show-plugin?id=obsidian-key-sequence-shortcut
https://github.com/anselmwang/obsidian-key-sequence-shortcut

Thanks very much in advance !
Cheers

**Comment by TreyMeyers** [comment]
I've added a brief comparison of features to the README file. Thank you.

**Comment by ngirard** [comment]
Great, thanks, Connor!
