### ISSUE TITLE
Template function is not running the templater code of triggering cursor

### ISSUE THREAD

**Issue by Gourav1910** [ConnorMeyers/obsidian-chorded-hotkeys#6]
Hi, thanks for this amazing plugin. It helped me lot. I recently discovered that when I input template then it don't run the templater code of triggering the cursor "tp.file.cursor". It is running the other templater code and replacing the desired result except this function. So could you please make it work if it is a bug? 

And one more request, is it possible to add an option to a setting where we setup our chord to do specific stuff. The setting has an option to choose for each chord that whether it will trigger when your cursor is in the note or it will trigger the chord without you being in the editing mode(means just like hotkey) and third option could be trigger in both condition. I mean it will be super powerful if it is possible because I have some quickadd capture setup and if I want to trigger that command then first I need to be in the editor so that I can type the chord to trigger it but I want to trigger it no matter where i am(i mean if it is possible).

**Comment by TreyMeyers** [comment]
The template chord will now trigger the tp.file.cursor calls if the Templater setting "Automatic jump to cursor" is set to true. 

I've added the ability to trigger chords outside of editor contexts to the roadmap, but I don't foresee this being available anytime soon.

Thanks.
